name: Update Image in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: daankoning/recursive-readme@v0.0.7
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update image
        file_pattern: example.png
