name: Update Image in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: daankoning/recursive-readme@v1.0.0
      with:
        auto-commit: 'true'
